<?php

namespace App\Console\Commands;

use App\Jobs\QueueDrillNoopJob;
use App\Models\QueueMetric;
use App\Services\QueueHealth\QueueHealthNotifier;
use App\Services\QueueHealth\QueueIncidentTracker;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Bus;

class QueueDrillCommand extends Command
{
    protected $signature = 'ops:queue-drill {--scenario=critical_incident : critical_incident|recovery|backlog_spike|batch_probe} {--json : Output as JSON}';

    protected $description = 'Run non-production queue incident drills for monitoring and operations readiness.';

    public function handle(QueueIncidentTracker $tracker, QueueHealthNotifier $notifier): int
    {
        if (app()->environment('production')) {
            $this->error('Queue drills are disabled in production.');

            return self::FAILURE;
        }

        $scenario = strtolower(trim((string) $this->option('scenario')));

        $report = match ($scenario) {
            'critical_incident' => $this->criticalIncidentReport(),
            'recovery' => $this->recoveryReport(),
            'backlog_spike' => $this->backlogSpikeReport(),
            'batch_probe' => $this->batchProbeReport(),
            default => null,
        };

        if ($report === null) {
            $this->error('Invalid scenario. Use: critical_incident, recovery, backlog_spike, batch_probe');

            return self::FAILURE;
        }

        $tracker->sync($report);
        $notifier->notify($report);

        if ((bool) $this->option('json')) {
            $this->line((string) json_encode([
                'scenario' => $scenario,
                'report' => $report,
            ], JSON_UNESCAPED_SLASHES));
        } else {
            $this->line(sprintf('Queue drill scenario "%s" executed.', $scenario));
            $this->line(sprintf('Status: %s', strtoupper((string) ($report['status'] ?? 'unknown'))));
            $this->line(sprintf('Issues: %d', count((array) ($report['issues'] ?? []))));
        }

        return self::SUCCESS;
    }

    /**
     * @return array{status: string, checked_at: string, issues: array<int, array<string, mixed>>, summary: array{critical: int, warning: int}, meta: array<string, mixed>}
     */
    private function criticalIncidentReport(): array
    {
        return [
            'status' => 'critical',
            'checked_at' => now()->toIso8601String(),
            'issues' => [[
                'key' => 'drill:critical_incident',
                'severity' => 'critical',
                'title' => 'Queue drill critical incident',
                'detail' => 'Synthetic incident generated by ops:queue-drill.',
                'lane' => 'parse',
            ]],
            'summary' => [
                'critical' => 1,
                'warning' => 0,
            ],
            'meta' => [
                'scenario' => 'critical_incident',
            ],
        ];
    }

    /**
     * @return array{status: string, checked_at: string, issues: array<int, array<string, mixed>>, summary: array{critical: int, warning: int}, meta: array<string, mixed>}
     */
    private function recoveryReport(): array
    {
        return [
            'status' => 'healthy',
            'checked_at' => now()->toIso8601String(),
            'issues' => [],
            'summary' => [
                'critical' => 0,
                'warning' => 0,
            ],
            'meta' => [
                'scenario' => 'recovery',
            ],
        ];
    }

    /**
     * @return array{status: string, checked_at: string, issues: array<int, array<string, mixed>>, summary: array{critical: int, warning: int}, meta: array<string, mixed>}
     */
    private function backlogSpikeReport(): array
    {
        $definition = (array) config('queue_health.lanes.parse', []);
        $driver = (string) ($definition['driver'] ?? 'redis_parse');
        $queue = (string) ($definition['queue'] ?? 'parse');
        $depthThreshold = max(1, (int) ($definition['max_depth'] ?? 20));
        $ageThreshold = max(1, (int) ($definition['max_oldest_age_seconds'] ?? 900));

        QueueMetric::create([
            'driver' => $driver,
            'queue' => $queue,
            'depth' => $depthThreshold + 25,
            'failed_count' => 0,
            'oldest_age_seconds' => $ageThreshold + 120,
            'throughput_per_min' => 1,
            'captured_at' => now(),
        ]);

        return [
            'status' => 'critical',
            'checked_at' => now()->toIso8601String(),
            'issues' => [[
                'key' => sprintf('drill:backlog_spike:%s:%s', $driver, $queue),
                'severity' => 'critical',
                'title' => 'Queue drill backlog spike',
                'detail' => 'Synthetic backlog spike generated for parse lane.',
                'lane' => 'parse',
            ]],
            'summary' => [
                'critical' => 1,
                'warning' => 0,
            ],
            'meta' => [
                'scenario' => 'backlog_spike',
                'driver' => $driver,
                'queue' => $queue,
            ],
        ];
    }

    /**
     * @return array{status: string, checked_at: string, issues: array<int, array<string, mixed>>, summary: array{critical: int, warning: int}, meta: array<string, mixed>}
     */
    private function batchProbeReport(): array
    {
        $jobs = [];
        $label = 'batch_probe_'.now()->format('Ymd_His');

        for ($i = 0; $i < 10; $i++) {
            $jobs[] = new QueueDrillNoopJob('parse', $label);
        }

        $batch = Bus::batch($jobs)
            ->name('queue-drill-'.$label)
            ->allowFailures()
            ->dispatch();

        return [
            'status' => 'warning',
            'checked_at' => now()->toIso8601String(),
            'issues' => [[
                'key' => 'drill:batch_probe:'.$batch->id,
                'severity' => 'warning',
                'title' => 'Queue drill batch probe dispatched',
                'detail' => 'Synthetic batch dispatched for Horizon /batches verification.',
                'lane' => 'parse',
            ]],
            'summary' => [
                'critical' => 0,
                'warning' => 1,
            ],
            'meta' => [
                'scenario' => 'batch_probe',
                'batch_id' => $batch->id,
                'jobs' => count($jobs),
            ],
        ];
    }
}
