<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class EngineSetting extends Model
{
    protected $fillable = [
        'engine_paused',
        'enhanced_mode_enabled',
        'role_accounts_behavior',
        'role_accounts_list',
        'catch_all_policy',
        'catch_all_promote_threshold',
        'cache_only_mode_enabled',
        'cache_only_miss_status',
        'cache_capacity_mode',
        'cache_batch_size',
        'cache_consistent_read',
        'cache_ondemand_max_batches_per_second',
        'cache_ondemand_sleep_ms_between_batches',
        'cache_provisioned_max_batches_per_second',
        'cache_provisioned_sleep_ms_between_batches',
        'cache_provisioned_max_retries',
        'cache_provisioned_backoff_base_ms',
        'cache_provisioned_backoff_max_ms',
        'cache_provisioned_jitter_enabled',
        'cache_failure_mode',
        'cache_writeback_enabled',
        'cache_writeback_statuses',
        'cache_writeback_batch_size',
        'cache_writeback_max_writes_per_second',
        'cache_writeback_retry_attempts',
        'cache_writeback_backoff_base_ms',
        'cache_writeback_backoff_max_ms',
        'cache_writeback_failure_mode',
        'cache_writeback_test_mode_enabled',
        'cache_writeback_test_table',
        'provider_policies',
        'tempfail_retry_enabled',
        'tempfail_retry_max_attempts',
        'tempfail_retry_backoff_minutes',
        'tempfail_retry_reasons',
        'reputation_window_hours',
        'reputation_min_samples',
        'reputation_tempfail_warn_rate',
        'reputation_tempfail_critical_rate',
        'show_single_checks_in_admin',
        'monitor_enabled',
        'monitor_interval_minutes',
        'monitor_rbl_list',
        'monitor_dns_mode',
        'monitor_dns_server_ip',
        'monitor_dns_server_port',
        'metrics_source',
        'queue_connection',
        'cache_store',
        'horizon_enabled',
    ];

    protected $casts = [
        'engine_paused' => 'boolean',
        'enhanced_mode_enabled' => 'boolean',
        'catch_all_promote_threshold' => 'integer',
        'cache_only_mode_enabled' => 'boolean',
        'cache_batch_size' => 'integer',
        'cache_consistent_read' => 'boolean',
        'cache_ondemand_max_batches_per_second' => 'integer',
        'cache_ondemand_sleep_ms_between_batches' => 'integer',
        'cache_provisioned_max_batches_per_second' => 'integer',
        'cache_provisioned_sleep_ms_between_batches' => 'integer',
        'cache_provisioned_max_retries' => 'integer',
        'cache_provisioned_backoff_base_ms' => 'integer',
        'cache_provisioned_backoff_max_ms' => 'integer',
        'cache_provisioned_jitter_enabled' => 'boolean',
        'cache_writeback_enabled' => 'boolean',
        'cache_writeback_statuses' => 'array',
        'cache_writeback_batch_size' => 'integer',
        'cache_writeback_max_writes_per_second' => 'integer',
        'cache_writeback_retry_attempts' => 'integer',
        'cache_writeback_backoff_base_ms' => 'integer',
        'cache_writeback_backoff_max_ms' => 'integer',
        'cache_writeback_test_mode_enabled' => 'boolean',
        'provider_policies' => 'array',
        'tempfail_retry_enabled' => 'boolean',
        'tempfail_retry_max_attempts' => 'integer',
        'reputation_window_hours' => 'integer',
        'reputation_min_samples' => 'integer',
        'reputation_tempfail_warn_rate' => 'decimal:2',
        'reputation_tempfail_critical_rate' => 'decimal:2',
        'show_single_checks_in_admin' => 'boolean',
        'monitor_enabled' => 'boolean',
        'monitor_interval_minutes' => 'integer',
        'monitor_dns_server_port' => 'integer',
        'horizon_enabled' => 'boolean',
    ];
}
